In [15]:
# Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np

In [9]:
# Read in the california housing data set
housing_data = pd.read_csv('../Resources/California_Housing.csv')
housing_data

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,5.2742,17.0,8.908654,1.884615,351.0,1.687500,32.98,-117.27
1,1.8438,52.0,3.069847,1.044293,2382.0,4.057922,34.07,-118.26
2,7.0691,13.0,6.689697,1.009697,2444.0,2.962424,37.57,-121.87
3,5.4719,38.0,5.890080,0.957105,1228.0,3.292225,37.52,-122.28
4,4.0156,35.0,6.195312,1.171875,669.0,5.226562,33.93,-117.41
...,...,...,...,...,...,...,...,...
2995,4.5724,4.0,6.837037,1.229630,352.0,2.607407,35.10,-117.98
2996,3.6031,52.0,3.702592,1.062756,1438.0,1.961801,37.77,-122.43
2997,5.2820,24.0,5.918495,1.000000,950.0,2.978056,32.85,-117.00
2998,1.3668,52.0,2.673635,1.089431,1515.0,1.759582,37.79,-122.41
2999,4.9688,15.0,6.185950,1.004132,730.0,3.016529,38.68,-121.25

In [17]:
# Determine which measure of central tendency is most appropriate to describe the Population
population = housing_data['Population']

mean_numpy = np.mean(population)
print(f"The mean population in Cali is {mean_numpy}")

median_numpy = np.median(population)
print(f"The median population in Cali is {median_numpy}")

mode_scipy = st.mode(population)
print(f"The mode population is {mode_scipy}")

The mean population in Cali is 1387.9633333333334
The median population in Cali is 1152.5
The mode population is ModeResult(mode=array([1128.]), count=array([8]))

C:\Users\Luis Santamaria\AppData\Local\Temp\ipykernel_944\2500716425.py:10: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_scipy = st.mode(population)

In [4]:
# Determine if the house age in California is normally distributed using a small and large sample size.

In [5]:
# Determine if there are any potential outliers in the average occupancy in California

In [6]:
# With the potential outliers, what is the lowest and highest median income (in $1000s) observed?

In [7]:
# Bonus - plot the latitude and longitude of the California housing data using Matplotlib, color the data points using the median income of the block.